#!/usr/bin/env python3
"""Quantify how much of the KG rubric lift is instruction priming rather than graph content.

The kg-empty run (outputs/kg_empty_priming, judged 2026-04-24) sends the identical
KG system prompt with an empty facts block. Comparing it against the baseline and
kg arms on the same PRs splits the observed kg lift into a priming share and a
content share.

The control covers five PRs and predates the v2 rebuild, so the comparison is
reported against both the v1 panel (era-matched stimuli) and the v2 panel
(era-mismatched but the headline of record). No API calls; reads judged output only.

Output: results/KG_EMPTY_PRIMING_CONTROL.md
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRIMING = ROOT / "results/checklist_evaluation_llm_multi__kgempty_priming.json"
PANELS = {
    "v1": ROOT / "results/checklist_evaluation_llm_multi.json",
    "v2": ROOT / "results/checklist_evaluation_llm_multi__v2.json",
}
OUT = ROOT / "results/KG_EMPTY_PRIMING_CONTROL.md"


def load_scores(path):
    """Return {(pr_id, mode): (total, kg_relevant)} from a judged panel file."""
    data = json.loads(path.read_text())
    scores = {}
    for ev in data["evaluations"]:
        key = (ev["pr_id"], ev["mode"])
        scores[key] = (ev["total_score"], ev["kg_relevant_score"])
    return scores


def mean(values):
    return sum(values) / len(values) if values else float("nan")


def main():
    priming = load_scores(PRIMING)
    pr_ids = sorted({pr for pr, _ in priming})

    lines = [
        "# KG-empty priming control — how much of the lift is the instruction?",
        "",
        "**Question.** The `kg` prompt differs from `baseline` in two ways: it carries",
        "repository facts, and it instructs the model to use them. If the rubric lift",
        "came from the instruction alone, an identical prompt with an *empty* facts",
        "block would reproduce it.",
        "",
        f"**Control run.** `outputs/kg_empty_priming`, judged 2026-04-24 by the same",
        "three-judge panel with the same aggregation rule. Covers "
        f"{len(pr_ids)} PRs: {', '.join(str(p) for p in pr_ids)}.",
        "",
        "**Era caveat.** The control predates the v2 rebuild, so it is era-matched to",
        "the v1 panel and era-mismatched to the v2 headline. Both comparisons are",
        "reported; neither is quoted without its era.",
        "",
        "Generated by `scripts/compare_kg_empty_priming.py` (no API calls).",
        "",
    ]

    for era, path in PANELS.items():
        if not path.exists():
            lines += [f"## {era}: panel file missing ({path.name})", ""]
            continue
        panel = load_scores(path)
        covered = [p for p in pr_ids if (p, "baseline") in panel and (p, "kg") in panel]
        missing = [p for p in pr_ids if p not in covered]

        lines += [
            f"## Against the {era} panel (`{path.name}`)",
            "",
            f"PRs available in both: {', '.join(str(p) for p in covered) or 'none'}."
            + (f" Missing: {', '.join(str(p) for p in missing)}." if missing else ""),
            "",
            "| PR | baseline | kg-empty | kg | priming share of lift |",
            "|---:|---:|---:|---:|---:|",
        ]
        if not covered:
            lines += ["", "No overlap; nothing to report.", ""]
            continue

        for p in covered:
            base, base_kgr = panel[(p, "baseline")]
            full, full_kgr = panel[(p, "kg")]
            empty, empty_kgr = priming[(p, "kgempty")]
            lift = full - base
            share = f"{(empty - base) / lift:+.0%}" if lift else "n/a (no lift)"
            lines.append(f"| {p} | {base} | {empty} | {full} | {share} |")

        base_m = mean([panel[(p, "baseline")][0] for p in covered])
        empty_m = mean([priming[(p, "kgempty")][0] for p in covered])
        full_m = mean([panel[(p, "kg")][0] for p in covered])
        base_k = mean([panel[(p, "baseline")][1] for p in covered])
        empty_k = mean([priming[(p, "kgempty")][1] for p in covered])
        full_k = mean([panel[(p, "kg")][1] for p in covered])

        lines += [
            f"| **mean** | **{base_m:.1f}** | **{empty_m:.1f}** | **{full_m:.1f}** | |",
            "",
            f"Total /25: baseline {base_m:.2f}, kg-empty {empty_m:.2f}, kg {full_m:.2f} "
            f"(priming {empty_m - base_m:+.2f}, content {full_m - empty_m:+.2f}).",
            "",
            f"KG-relevant /9: baseline {base_k:.2f}, kg-empty {empty_k:.2f}, kg {full_k:.2f} "
            f"(priming {empty_k - base_k:+.2f}, content {full_k - empty_k:+.2f}).",
            "",
        ]

    lines += [
        "## How to read this",
        "",
        "`kg-empty − baseline` is the priming component: what the instruction buys with",
        "no facts attached. `kg − kg-empty` is the content component: what the facts add",
        "on top of the instruction. With five PRs neither component supports a",
        "significance claim, and the sign pattern is what the control is for.",
        "",
    ]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
