#!/usr/bin/env python3
"""generate_paper_tables.py — emit the conference paper's LaTeX tables.

Every table is generated from the raw result artefacts so that no number in
the paper is transcribed by hand. Output goes to the Overleaf working clone
(`paper/2026-08-12/draft/tables/`) as standalone `.tex` files that `main.tex`
pulls in with \\input.

Reads:
  results/BOOTSTRAP_STATS_v2.json                  Experiment 1 (era 2, n=40)
  results/BOOTSTRAP_STATS_joern.json               builder sensitivity (n=35)
  results/checklist_evaluation_llm_multi__v2.json  win attribution
  experiments/2026-07-05_injection_exp2/out/results.json    Experiment 2
  experiments/2026-07-05_injection_exp2/out/manifest.json   band composition

Writes:
  tables/exp1_means.tex          T1  per-mode means with bootstrap CIs
  tables/exp1_deltas.tex         T2  paired differences vs baseline
  tables/exp1_builder.tex        T3  grep vs Joern builder, original rubric
  tables/exp1_attribution.tex    T4  win concentration (placebo-band test)
  tables/exp2_structural.tex     T5  structural detection by arm
  tables/exp2_local.tex          T6  local-control placebo parity
  tables/config.tex              T7  generation and scoring configuration

Verified by paper/2026-08-12/verify_paper_numbers.py.
"""

from __future__ import annotations

import json
import os
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper", "2026-08-12", "draft", "tables")

MODE_LABEL = {
    "baseline": "baseline (diff only)",
    "kg": "kg",
    "rag": "rag",
    "hybrid": "hybrid (kg+rag)",
}
ARM_LABEL = {
    "baseline": "baseline (diff only)",
    "rag": "rag",
    "hybrid": "hybrid (kg+rag)",
    "kg": "kg (deployed CPG)",
    "kg_joern_inherit": "kg + inheritance edges",
    "kg_idealised": "kg idealised (ceiling)",
}
# Narrower variants for the single-column placebo table.
ARM_SHORT = {
    "baseline": "baseline",
    "rag": "rag",
    "hybrid": "hybrid",
    "kg": "kg",
    "kg_joern_inherit": "kg + inherit.",
    "kg_idealised": "kg idealised",
}
KG_RELEVANT = {"F3", "F4", "T1", "T2", "T3", "M1", "M3", "C2", "Q2"}

BANNER = ("% Generated by scripts/generate_paper_tables.py — do not edit by hand.\n"
          "% Source: {src}\n")


def load(rel: str):
    with open(os.path.join(ROOT, rel)) as fh:
        return json.load(fh)


def write(name: str, src: str, body: str) -> None:
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w") as fh:
        fh.write(BANNER.format(src=src) + body.rstrip() + "\n")
    print(f"wrote tables/{name}")


def ci(d: dict, places: int = 2) -> str:
    return f"{d['mean']:.{places}f} [{d['ci_lo']:.{places}f}, {d['ci_hi']:.{places}f}]"


def stars(p: float) -> str:
    if p < 0.001:
        return r"\textsuperscript{***}"
    if p < 0.01:
        return r"\textsuperscript{**}"
    if p < 0.05:
        return r"\textsuperscript{*}"
    return ""


def fmt_p(p: float) -> str:
    if p < 0.0001:
        return r"$<$0.0001"
    if p >= 0.9995:
        return "1.00"
    return f"{p:.4f}".rstrip("0").rstrip(".")


# ------------------------------------------------------------------ T1, T2, T3
def exp1_means() -> None:
    d = load("results/BOOTSTRAP_STATS_v2.json")
    rows = []
    for mode in ("baseline", "kg", "rag", "hybrid"):
        m = d["by_mode"][mode]
        rows.append(f"{mode} & {ci(m['total'])} & {ci(m['kg_relevant'])} \\\\")
    body = r"""\begin{table}[t]
\centering
\caption{Experiment 1: mean rubric score per condition with 95\% percentile
bootstrap confidence intervals ($B=10\,000$, seed 2026), $n=40$ pull
requests. \emph{baseline} is diff-only and \emph{hybrid} is kg+rag. Total is
out of 25 criteria; the dependency subset is the nine pre-registered criteria
the graph context is designed to affect.}
\label{tab:exp1-means}
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{lcc}
\toprule
Condition & Total /25 & Dependency /9 \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    write("exp1_means.tex", "results/BOOTSTRAP_STATS_v2.json", body)


def exp1_deltas() -> None:
    d = load("results/BOOTSTRAP_STATS_v2.json")
    rows = []
    for mode in ("kg", "rag", "hybrid"):
        v = d["vs_baseline"][mode]
        t, k = v["total_diff"], v["kg_relevant_diff"]
        rows.append(
            f"{MODE_LABEL[mode]} & {t['mean']:+.2f} [{t['ci_lo']:+.2f}, {t['ci_hi']:+.2f}] & "
            f"{fmt_p(t['p_value'])}{stars(t['p_value'])} & {t['d_z']:+.2f} & "
            f"{k['mean']:+.2f} [{k['ci_lo']:+.2f}, {k['ci_hi']:+.2f}] & "
            f"{fmt_p(k['p_value'])}{stars(k['p_value'])} & {k['d_z']:+.2f} \\\\")
    body = r"""\begin{table*}[t]
\centering
\caption{Experiment 1: paired differences against the diff-only baseline on
the same pull request. Two-sided paired sign-flip permutation test
($B=20\,000$, seed 2026); $d_z$ is the paired Cohen's $d$.
\textsuperscript{*}$p<.05$, \textsuperscript{**}$p<.01$,
\textsuperscript{***}$p<.001$. Each context type reaches significance on the
metric it targets, and the hybrid on both.}
\label{tab:exp1-deltas}
\begin{tabular}{lccccccc}
\toprule
& \multicolumn{3}{c}{Total /25} & \multicolumn{3}{c}{Dependency /9} \\
\cmidrule(lr){2-4} \cmidrule(lr){5-7}
Mode vs baseline & $\Delta$ [95\% CI] & $p$ & $d_z$ & $\Delta$ [95\% CI] & $p$ & $d_z$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}"""
    write("exp1_deltas.tex", "results/BOOTSTRAP_STATS_v2.json", body)


def exp1_builder() -> None:
    a = load("results/BOOTSTRAP_STATS_v2.json")["vs_baseline"]["kg"]
    b = load("results/BOOTSTRAP_STATS_joern.json")["vs_baseline"]["kg"]
    rows = []
    for label, n, v in (("Import/AST resolver", 40, a), ("Code property graph", 35, b)):
        t, k = v["total_diff"], v["kg_relevant_diff"]
        rows.append(
            f"{label} & {n} & "
            f"{k['mean']:+.2f} [{k['ci_lo']:+.2f}, {k['ci_hi']:+.2f}] & "
            f"{fmt_p(k['p_value'])}{stars(k['p_value'])} & {k['d_z']:+.2f} & "
            f"{t['mean']:+.2f} [{t['ci_lo']:+.2f}, {t['ci_hi']:+.2f}] & "
            f"{fmt_p(t['p_value'])}{stars(t['p_value'])} & {t['d_z']:+.2f} \\\\")
    body = r"""\begin{table*}[t]
\centering
\caption{Builder sensitivity within Experiment 1: the graph arm against the
same diff-only baseline, under two graph construction methods, scored on the
\emph{same} 25-criterion rubric by the \emph{same} three-judge panel. The
code-property-graph run excludes five Go pull requests its frontend cannot
parse, hence $n=35$. A stronger resolver leaves the dependency effect broadly
similar but moves the total-score effect from inconclusive to significant.}
\label{tab:exp1-builder}
\begin{tabular}{llcccccc}
\toprule
& & \multicolumn{3}{c}{Dependency /9} & \multicolumn{3}{c}{Total /25} \\
\cmidrule(lr){3-5} \cmidrule(lr){6-8}
Graph construction & $n$ & $\Delta$ [95\% CI] & $p$ & $d_z$ & $\Delta$ [95\% CI] & $p$ & $d_z$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}"""
    write("exp1_builder.tex",
          "results/BOOTSTRAP_STATS_v2.json + results/BOOTSTRAP_STATS_joern.json", body)


def exp1_attribution() -> None:
    d = load("results/checklist_evaluation_llm_multi__v2.json")
    cells = {(e["pr_id"], e["mode"]): {c["criterion_id"]: c["score"]
                                      for c in e["criteria_scores"]}
             for e in d["evaluations"]}
    prs = sorted({e["pr_id"] for e in d["evaluations"]})
    rows = []
    for mode in ("kg", "rag"):
        tally = {True: [0, 0], False: [0, 0]}  # is_dependency -> [wins, losses]
        for pr in prs:
            base, treat = cells[(pr, "baseline")], cells[(pr, mode)]
            for crit, b in base.items():
                dep = crit in KG_RELEVANT
                if treat[crit] == 1 and b == 0:
                    tally[dep][0] += 1
                elif treat[crit] == 0 and b == 1:
                    tally[dep][1] += 1
        dw, dl = tally[True]
        nw, nl = tally[False]
        rows.append(f"{MODE_LABEL[mode]} & {dw} & {dl} & \\textbf{{{dw - dl:+}}} & "
                    f"{nw} & {nl} & \\textbf{{{nw - nl:+}}} \\\\")
    body = r"""\begin{table}[t]
\centering
\caption{Where the gains land (Experiment 1, $n=40$). A win is a criterion the
treatment satisfies and the baseline does not, on the same pull request. The
sixteen non-dependency criteria act as a built-in negative control: a generic
quality lift would spread evenly across both bands.}
\label{tab:exp1-attribution}
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{lcccccc}
\toprule
& \multicolumn{3}{c}{Dependency (9 criteria)} & \multicolumn{3}{c}{Other (16 criteria)} \\
\cmidrule(lr){2-4} \cmidrule(lr){5-7}
Mode & W & L & net & W & L & net \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    write("exp1_attribution.tex", "results/checklist_evaluation_llm_multi__v2.json", body)


# ---------------------------------------------------------------------- T5, T6
def exp2_tables() -> None:
    src = "experiments/2026-07-05_injection_exp2/out/results.json"
    d = load(src)
    det, con = d["detection"], d["contrasts"]

    order = ("baseline", "rag", "hybrid", "kg", "kg_joern_inherit", "kg_idealised")
    rows = []
    for arm in order:
        s = det[f"structural:{arm}"]
        c = con.get(f"structural:{arm}-vs-baseline")
        delta = (f"{c['delta']:+.2f} [{c['ci95'][0]:+.2f}, {c['ci95'][1]:+.2f}] & "
                 f"{fmt_p(c['p_perm'])}{stars(c['p_perm'])}") if c else "--- & ---"
        bold = r"\textbf{" if arm == "kg" else ""
        end = "}" if arm == "kg" else ""
        rows.append(f"{bold}{ARM_LABEL[arm]}{end} & {s['detected']}/{s['n']} & "
                    f"{s['rate']:.2f} [{s['ci95'][0]:.2f}, {s['ci95'][1]:.2f}] & {delta} \\\\")

    body = r"""\begin{table*}[t]
\centering
\caption{Experiment 2, structural bands ($n=28$): detection of an injected
defect whose consequence lies outside the changed file. Rates with 95\%
bootstrap confidence intervals; contrasts by paired permutation test
($B=20\,000$, seed 2026). The diff-only baseline never detects one.}
\label{tab:exp2-structural}
\begin{tabular}{lcccc}
\toprule
Arm & Detected & Rate [95\% CI] & $\Delta$ vs baseline [95\% CI] & $p$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table*}"""
    write("exp2_structural.tex", src, body)

    rows = []
    for arm in order:
        s = det[f"local_control:{arm}"]
        c = con.get(f"local_control:{arm}-vs-baseline")
        delta = f"{c['delta']:+.2f} [{c['ci95'][0]:+.2f}, {c['ci95'][1]:+.2f}]" if c else "---"
        rows.append(f"{ARM_SHORT[arm]} & {s['detected']}/{s['n']} & {s['rate']:.2f} & {delta} \\\\")
    body = r"""\begin{table}[t]
\centering
\caption{Experiment 2, local-control bands ($n=12$): the placebo check. The
defect is visible inside the diff, so every arm should detect it and no arm
should gain from added context. All differences fall inside the
pre-registered parity window $[-0.15, +0.15]$.}
\label{tab:exp2-local}
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{lccc}
\toprule
Arm & Det. & Rate & $\Delta$ vs base. [95\% CI] \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}"""
    write("exp2_local.tex", src, body)


# -------------------------------------------------------------------------- T7
def config_table() -> None:
    man = load("experiments/2026-07-05_injection_exp2/out/manifest.json")
    bands = Counter(i["band"] for i in man["injections"])
    struct = sum(v for k, v in bands.items() if k.startswith("S"))
    local = sum(v for k, v in bands.items() if k.startswith("L"))
    panel = load("results/checklist_evaluation_llm_multi__v2.json")["metadata"]["judges"]
    judges = ", ".join(j.split(":")[1] for j in panel)
    body = r"""\begin{table}[t]
\centering
\caption{Configuration of both experiments. Generation temperatures differ
because the two pipelines call different entry points; within an experiment
every arm shares one setting, so all contrasts are internally valid. No
generation seed is sent to the model, so Experiment 1's determinism rests on
$T=0$.}
\label{tab:config}
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{lcc}
\toprule
& Experiment 1 & Experiment 2 \\
\midrule
Unit & merged PR & injected defect \\
""" + f"""$n$ & 40 & {struct + local} ({struct} struct., {local} control) \\\\
Repositories & 5 & 3 \\\\
Generator & gpt-4o & gpt-4o \\\\
Temperature & 0.0 & 0.3 \\\\
Diff cap (chars) & 50\\,000 & 12\\,000 \\\\
Judges & \\multicolumn{{2}}{{c}}{{{judges}}} \\\\
Aggregation & \\multicolumn{{2}}{{c}}{{majority of three, ties to 0}} \\\\
Outcome & rubric /25 & defect detected \\\\
Ground truth & LLM panel & static oracle \\\\
Statistics seed & \\multicolumn{{2}}{{c}}{{2026}} \\\\
""" + r"""\bottomrule
\end{tabular}
\end{table}"""
    write("config.tex",
          "results/checklist_evaluation_llm_multi__v2.json + injection manifest", body)


def main() -> None:
    exp1_means()
    exp1_deltas()
    exp1_builder()
    exp1_attribution()
    exp2_tables()
    config_table()
    print(f"\nall tables written to {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
