#!/usr/bin/env python3
"""generate_paper_figures.py — emit the conference paper's figures as pgfplots.

Figure 1 is the paper's headline: cross-file defect detection by arm, with the
placebo band beside it, so a reader sees in one glance that the graph
advantage appears only where structure matters.

The figure is emitted as LaTeX (pgfplots) rather than a raster or a
matplotlib PDF. That keeps the plot vector, makes it use the document's own
fonts, and avoids adding a Python plotting dependency to a pinned
environment.

Reads:
  experiments/2026-07-05_injection_exp2/out/results.json

Writes:
  paper/2026-08-12/draft/figures/detection_ladder.tex

Requires \\usepackage{pgfplots} in the preamble. Cited as Fig. 1 (Section V).
"""

from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "paper", "2026-08-12", "draft", "figures")

# Bottom-to-top in the plot: weakest context first, idealised ceiling last.
ARMS = [
    ("baseline", "baseline"),
    ("rag", "rag"),
    ("hybrid", "hybrid"),
    ("kg", "kg"),
    ("kg_joern_inherit", "kg+inherit."),
    ("kg_idealised", "kg idealised"),
]


def load_detection() -> dict:
    with open(os.path.join(
            ROOT, "experiments/2026-07-05_injection_exp2/out/results.json")) as fh:
        return json.load(fh)["detection"]


def series(det: dict, band: str) -> tuple[str, str]:
    """Return (coordinate block, label block) for one band."""
    coords, labels = [], []
    for idx, (arm, _) in enumerate(ARMS):
        s = det[f"{band}:{arm}"]
        lo, hi = s["ci95"]
        coords.append(f"        ({s['rate']:.4f},{idx}) "
                      f"+- (0,0) -= (0,0)  % {arm} {s['detected']}/{s['n']}")
        # Asymmetric error bars are given explicitly per point.
        coords[-1] = (f"        ({s['rate']:.4f},{idx}) "
                      f"+- ({hi - s['rate']:.4f},0) -= ({s['rate'] - lo:.4f},0)")
        labels.append(f"      \\node[anchor=west,font=\\scriptsize,gray!60!black] "
                      f"at (axis cs:{hi + 0.03:.4f},{idx}) {{{s['detected']}/{s['n']}}};")
    return "\n".join(coords), "\n".join(labels)


def main() -> None:
    det = load_detection()
    struct_coords, struct_labels = series(det, "structural")
    local_coords, local_labels = series(det, "local_control")
    ytick_labels = ",".join(lbl for _, lbl in ARMS)

    tex = r"""% Generated by scripts/generate_paper_figures.py — do not edit by hand.
% Source: experiments/2026-07-05_injection_exp2/out/results.json
% Requires \usepackage{pgfplots} and \pgfplotsset{compat=1.18}.
\begin{figure*}[t]
\centering
\pgfplotsset{
  detbar/.style={
    xbar, width=0.47\textwidth, height=4.1cm,
    xmin=0, xmax=1.19, xtick={0,0.25,0.5,0.75,1.0},
    bar width=7pt, y=0.52cm,
    axis lines*=left, axis line style={gray!50},
    xmajorgrids, grid style={gray!22, line width=0.4pt},
    tick label style={font=\scriptsize},
    xlabel style={font=\scriptsize, yshift=2pt},
    title style={font=\small, align=center, yshift=1pt},
    error bars/x dir=both, error bars/x explicit,
    error bars/error bar style={gray!70!black, line width=0.6pt},
    error bars/error mark options={rotate=90, mark size=1.4pt, gray!70!black},
    ytick={0,1,2,3,4,5},
    enlarge y limits={abs=0.5},
    clip=false,
  },
}
\begin{tikzpicture}
\begin{axis}[detbar,
    yticklabels={""" + ytick_labels + r"""},
    ytick style={draw=none},
    xlabel={detection rate},
    title={Structural defects ($n{=}28$)\\\scriptsize consequence \emph{outside} the changed file},
  ]
  \addplot+[draw=none, fill=blue!58!black!78] plot coordinates {
""" + struct_coords + r"""
  };
""" + struct_labels + r"""
\end{axis}
\begin{axis}[detbar, at={(0.5\textwidth,0)}, anchor=south west,
    yticklabels={,,},
    ytick style={draw=none},
    xlabel={detection rate},
    title={Local controls ($n{=}12$)\\\scriptsize consequence \emph{inside} the diff},
  ]
  \addplot+[draw=none, fill=gray!45] plot coordinates {
""" + local_coords + r"""
  };
""" + local_labels + r"""
\end{axis}
\end{tikzpicture}
\caption{Defect detection by arm, with 95\% bootstrap confidence intervals and
raw counts. Left: defects whose consequence provably lies outside the changed
file. The diff-only baseline detects none, embedding retrieval detects one,
and graph context detects fifteen; the idealised resolver shows how much of
the remaining gap belongs to graph construction rather than to the model.
Right: the placebo band, where the defect is visible in the diff and no arm
should gain from added context --- and none does. The contrast between the two
panels is what distinguishes a structural capability from a context-volume
artefact.}
\label{fig:detection-ladder}
\end{figure*}"""

    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, "detection_ladder.tex")
    with open(path, "w") as fh:
        fh.write(tex.rstrip() + "\n")
    print(f"wrote {os.path.relpath(path, ROOT)}")


if __name__ == "__main__":
    main()
